import type {
  AdminUser,
  AlertItem,
  CoachProfile,
  CustomerProfile,
  FaqItem,
  LessonItem,
  MessageThread,
  ProductGuideItem,
} from "./types";

export const currentCoach: CoachProfile = {
  id: "coach-001",
  name: "林知恩 Chloe",
  avatar: "🌿",
  title: "资深 Journey Coach",
  bio: "专注体重管理与营养陪伴 6 年，擅长帮助顾客建立可持续的生活习惯。相信每一天都是新的旅程。",
  phone: "+60 12-345 6789",
  wechat: "chloe_misu",
  referralCode: "CHLOE688",
  totalCustomers: 48,
  activeThisWeek: 35,
  yearsExperience: 6,
  rating: 4.9,
  specialties: ["体重管理", "营养搭配", "习惯养成"],
};

export const currentCustomer: CustomerProfile = {
  id: "cust-001",
  name: "王美琪",
  avatar: "🌸",
  planLength: 60,
  currentDay: 18,
  startDate: "2026-06-24",
  startWeight: 68.2,
  currentWeight: 63.5,
  targetWeight: 58,
  startWaist: 82,
  currentWaist: 76.5,
  height: 160,
  age: 32,
  gender: "female",
  phone: "+60 13-888 2222",
  coachId: "coach-001",
  streakDays: 18,
  todayCompletionRate: 72,
  todayMisuScore: 86,
  checkinRate: 94,
  tags: ["高活跃", "饮食达人"],
  lastCheckIn: "今天 08:20",
  productStock: "low",
  weightTrend: [
    { label: "W1", value: 68.2 },
    { label: "W2", value: 66.8 },
    { label: "W3", value: 65.1 },
    { label: "第18天", value: 63.5 },
  ],
  waistTrend: [
    { label: "W1", value: 82 },
    { label: "W2", value: 80.2 },
    { label: "W3", value: 78 },
    { label: "第18天", value: 76.5 },
  ],
  scoreTrend: [
    { label: "周一", value: 78 },
    { label: "周二", value: 82 },
    { label: "周三", value: 75 },
    { label: "周四", value: 88 },
    { label: "周五", value: 91 },
    { label: "周六", value: 84 },
    { label: "今天", value: 86 },
  ],
  nutritionTargets: { calories: 1500, protein: 90, carbs: 150, fat: 50, fiber: 25 },
  nutritionToday: {
    calories: 1120,
    protein: 68,
    carbs: 98,
    fat: 34,
    fiber: 16,
    water: 1400,
    waterTarget: 2000,
  },
  tasks: [
    { id: "t1", title: "早餐打卡", description: "记录今日早餐照片", done: true, icon: "🍳" },
    { id: "t2", title: "喝水 2000ml", description: "已完成 1400ml", done: false, icon: "💧" },
    { id: "t3", title: "每日体重打卡", description: "体重 + 状态记录", done: true, icon: "⚖️" },
    { id: "t4", title: "今日学习", description: "第 18 课：如何应对聚餐", done: false, icon: "📚" },
    { id: "t5", title: "晚餐打卡", description: "记录今日晚餐照片", done: false, icon: "🍽️" },
  ],
  meals: [
    {
      id: "m1",
      type: "breakfast",
      name: "燕麦牛奶配蓝莓",
      time: "08:15",
      photoEmoji: "🥣",
      portion: "约 320g",
      calories: 310,
      protein: 14,
      carbs: 45,
      fat: 8,
      fiber: 6,
      misuScore: 90,
      goodPoints: ["蛋白质充足", "纤维来源丰富", "含糖量控制得宜"],
      improvePoints: ["可以再增加一份坚果补充健康脂肪"],
      aiAdvice: "",
    },
    {
      id: "m2",
      type: "lunch",
      name: "鸡胸肉藜麦沙拉",
      time: "12:40",
      photoEmoji: "🥗",
      portion: "约 400g",
      calories: 480,
      protein: 38,
      carbs: 42,
      fat: 14,
      fiber: 9,
      misuScore: 88,
      goodPoints: ["优质蛋白来源", "蔬菜比例理想"],
      improvePoints: ["酱料建议减半", "可搭配一份水果补充维生素C"],
      aiAdvice: "",
    },
    {
      id: "m3",
      type: "snack",
      name: "希腊酸奶",
      time: "15:30",
      photoEmoji: "🍦",
      portion: "约 150g",
      calories: 130,
      protein: 12,
      carbs: 8,
      fat: 4,
      fiber: 0,
      misuScore: 82,
      goodPoints: ["高蛋白低脂选择"],
      improvePoints: ["可加入少量莓果提升纤维摄取"],
      aiAdvice: "",
    },
  ],
};

export const otherCustomers: CustomerProfile[] = [
  {
    ...currentCustomer,
    id: "cust-002",
    name: "陈嘉玲",
    avatar: "🌼",
    currentDay: 42,
    planLength: 90,
    currentWeight: 71.2,
    targetWeight: 62,
    startWeight: 79.5,
    streakDays: 3,
    todayCompletionRate: 20,
    todayMisuScore: 54,
    checkinRate: 61,
    tags: ["体重停滞"],
    lastCheckIn: "3 天前",
    productStock: "ok",
  },
  {
    ...currentCustomer,
    id: "cust-003",
    name: "李思敏",
    avatar: "🌷",
    currentDay: 7,
    planLength: 60,
    currentWeight: 58.9,
    targetWeight: 54,
    startWeight: 60.5,
    streakDays: 7,
    todayCompletionRate: 100,
    todayMisuScore: 95,
    checkinRate: 100,
    tags: ["新顾客", "高活跃"],
    lastCheckIn: "今天 07:10",
    productStock: "ok",
  },
  {
    ...currentCustomer,
    id: "cust-004",
    name: "周雅婷",
    avatar: "🌹",
    currentDay: 55,
    planLength: 60,
    currentWeight: 55.4,
    targetWeight: 54,
    startWeight: 63,
    streakDays: 0,
    todayCompletionRate: 0,
    todayMisuScore: 0,
    checkinRate: 48,
    tags: ["即将完成", "产品即将用完"],
    lastCheckIn: "4 天前",
    productStock: "low",
  },
  {
    ...currentCustomer,
    id: "cust-005",
    name: "郑晓彤",
    avatar: "🌻",
    currentDay: 30,
    planLength: 90,
    currentWeight: 66.8,
    targetWeight: 60,
    startWeight: 72,
    streakDays: 12,
    todayCompletionRate: 85,
    todayMisuScore: 79,
    checkinRate: 88,
    tags: ["饮食达人"],
    lastCheckIn: "今天 09:02",
    productStock: "out",
  },
];

export const allCustomers: CustomerProfile[] = [currentCustomer, ...otherCustomers];

export const coachAlerts: AlertItem[] = [
  {
    id: "a1",
    customerId: "cust-002",
    customerName: "陈嘉玲",
    avatar: "🌼",
    type: "weight-stall",
    title: "体重停滞 2 周",
    detail: "近 14 天体重变化小于 0.3kg，建议调整饮食计划或安排通话",
    severity: "high",
    daysAgo: 0,
  },
  {
    id: "a2",
    customerId: "cust-004",
    customerName: "周雅婷",
    avatar: "🌹",
    type: "no-checkin",
    title: "连续 4 天未打卡",
    detail: "最后一次打卡在 4 天前，建议主动关心",
    severity: "high",
    daysAgo: 4,
  },
  {
    id: "a3",
    customerId: "cust-005",
    customerName: "郑晓彤",
    avatar: "🌻",
    type: "low-stock",
    title: "产品即将用完",
    detail: "预估库存可维持 2 天，建议提醒补货",
    severity: "medium",
    daysAgo: 0,
  },
  {
    id: "a4",
    customerId: "cust-004",
    customerName: "周雅婷",
    avatar: "🌹",
    type: "low-score",
    title: "MISU Score 连续偏低",
    detail: "近 3 天平均分数低于 60 分",
    severity: "medium",
    daysAgo: 1,
  },
];

export const messageThreads: MessageThread[] = [
  {
    id: "th1",
    customerId: "cust-002",
    customerName: "陈嘉玲",
    avatar: "🌼",
    lastMessage: "教练，我这周体重都没什么变化，有点担心😟",
    lastTime: "10:24",
    unread: 2,
  },
  {
    id: "th2",
    customerId: "cust-003",
    customerName: "李思敏",
    avatar: "🌷",
    lastMessage: "谢谢教练的建议！今天的午餐我调整了份量",
    lastTime: "昨天",
    unread: 0,
  },
  {
    id: "th3",
    customerId: "cust-005",
    customerName: "郑晓彤",
    avatar: "🌻",
    lastMessage: "产品快用完了，可以帮我安排补货吗？",
    lastTime: "昨天",
    unread: 1,
  },
  {
    id: "th4",
    customerId: "cust-001",
    customerName: "王美琪",
    avatar: "🌸",
    lastMessage: "今天的沙拉超好吃，谢谢教练推荐！",
    lastTime: "周一",
    unread: 0,
  },
];

export const adminUsers: AdminUser[] = [
  { id: "u1", name: "林知恩 Chloe", email: "chloe@xmegami.com", role: "coach", status: "active", joinedAt: "2024-02-10" },
  { id: "u2", name: "王美琪", email: "meiqi@example.com", role: "customer", status: "active", joinedAt: "2026-06-24" },
  { id: "u3", name: "陈嘉玲", email: "jialing@example.com", role: "customer", status: "active", joinedAt: "2026-05-30" },
  { id: "u4", name: "Admin 主账号", email: "admin@xmegami.com", role: "admin", status: "active", joinedAt: "2023-11-01" },
  { id: "u5", name: "李思敏", email: "simin@example.com", role: "customer", status: "pending", joinedAt: "2026-07-05" },
  { id: "u6", name: "郑家豪 Marcus", email: "marcus@xmegami.com", role: "coach", status: "inactive", joinedAt: "2024-08-19" },
];

export const adminCoaches = [
  { id: "coach-001", name: "林知恩 Chloe", avatar: "🌿", customers: 48, activeThisWeek: 35, rating: 4.9, status: "active" as const },
  { id: "coach-002", name: "郑家豪 Marcus", avatar: "🌊", customers: 31, activeThisWeek: 20, rating: 4.7, status: "active" as const },
  { id: "coach-003", name: "许佩珊 Grace", avatar: "🌺", customers: 26, activeThisWeek: 19, rating: 4.8, status: "active" as const },
  { id: "coach-004", name: "杨志明 Kevin", avatar: "🍃", customers: 12, activeThisWeek: 3, rating: 4.5, status: "inactive" as const },
];

export const lessons: LessonItem[] = [
  { id: "l1", title: "第 1 课：认识你的身体", category: "基础知识", duration: "8 分钟", status: "published", views: 1204 },
  { id: "l2", title: "第 18 课：如何应对聚餐", category: "生活场景", duration: "6 分钟", status: "published", views: 892 },
  { id: "l3", title: "第 25 课：突破停滞期", category: "进阶技巧", duration: "10 分钟", status: "draft", views: 0 },
  { id: "l4", title: "第 30 课：维持期的心态调整", category: "心理建设", duration: "7 分钟", status: "published", views: 634 },
];

export const faqs: FaqItem[] = [
  { id: "f1", question: "MISU Score 是怎么计算的？", answer: "综合饮食均衡度、打卡完成率与目标达成进度计算。", category: "使用说明", status: "published" },
  { id: "f2", question: "可以更换 Journey Coach 吗？", answer: "可以，请联系客服协助安排更换。", category: "账户", status: "published" },
  { id: "f3", question: "拍照记录食物不准确怎么办？", answer: "可以手动调整份量或选择「食物不对」重新拍摄。", category: "使用说明", status: "draft" },
];

export const productGuides: ProductGuideItem[] = [
  { id: "p1", name: "MISU 代餐奶昔", category: "代餐", summary: "每份含 20g 优质蛋白，适合早餐或加餐使用", status: "published" },
  { id: "p2", name: "MISU 纤维饮", category: "机能饮品", summary: "帮助补充膳食纤维，建议餐前 30 分钟饮用", status: "published" },
  { id: "p3", name: "MISU 燃脂胶囊", category: "营养补充", summary: "搭配运动使用效果更佳", status: "draft" },
];

export const adminOverview = {
  totalCustomers: 520,
  totalCoaches: 68,
  activeToday: 312,
  avgCheckinRate: 76,
  plan60CompletionRate: 68,
  plan90CompletionRate: 54,
  pendingIssues: 9,
};
