-- Phase 7 — Coach Application Workflow + first-version Notification Center.
--
-- New business workflow layered ON TOP of the frozen Coach Capability
-- architecture (Phase 1~6.1). This migration does NOT alter any existing
-- table, policy, or RPC. Approval reuses the frozen admin_set_coach_access()
-- to actually grant the capability — the security model is unchanged.
--
-- A registered customer applies with their company Reseller Username; the
-- application enters an Admin review queue. Approve activates Coach capability;
-- Reject records a reason the applicant sees. Every submission is retained as
-- history. Internal Notes are Admin-only.

-- ---------- Status enum ----------
do $$ begin
  create type public.coach_application_status as enum ('pending', 'approved', 'rejected', 'withdrawn');
exception when duplicate_object then null; end $$;

-- ---------- coach_applications ----------
create table if not exists public.coach_applications (
  id uuid primary key default gen_random_uuid(),
  application_number bigint generated by default as identity,
  applicant_id uuid not null references public.profiles(id) on delete cascade,
  reseller_username text not null,
  status public.coach_application_status not null default 'pending',
  reject_reason text,
  internal_note text,                        -- Admin-only; never exposed to users
  submitted_at timestamptz not null default now(),
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists coach_applications_applicant_idx on public.coach_applications(applicant_id);
create index if not exists coach_applications_status_idx on public.coach_applications(status);
-- At most one open (pending) application per applicant. Withdrawn/rejected
-- rows stay as history and don't block a fresh submission.
create unique index if not exists coach_applications_one_pending_per_user
  on public.coach_applications(applicant_id) where status = 'pending';

-- RLS ENABLED WITH NO CLIENT-FACING POLICY: direct reads/writes by
-- authenticated/anon are denied. Users read via get_my_coach_applications()
-- (SECURITY DEFINER, omits internal_note); Admin reads via the service-role
-- API route. This is deliberate — RLS is row-level, so a permissive user
-- SELECT policy would expose the internal_note column. All writes go through
-- the SECURITY DEFINER RPCs below.
alter table public.coach_applications enable row level security;

-- ---------- notifications (first-version Notification Center) ----------
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  reject_reason text,
  action_label text,
  action_href text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_idx on public.notifications(user_id, created_at desc);
create index if not exists notifications_user_unread_idx on public.notifications(user_id) where read_at is null;

alter table public.notifications enable row level security;

-- Users may read their own notifications directly (no admin-only columns here).
-- Inserts happen only inside the review RPCs; marking-read goes through
-- mark_notification_read(), so no insert/update policy is granted.
drop policy if exists notifications_select_own on public.notifications;
create policy notifications_select_own on public.notifications
  for select using (user_id = auth.uid());

-- ============================================================
-- User-facing RPCs
-- ============================================================

-- Submit a new application. Any registered customer who is not already a Coach
-- and has no pending application. Reseller Username is normalised + format-
-- checked to the same rule admin_set_coach_access enforces at approval, so a
-- submission that could never be approved is rejected up front.
create or replace function public.submit_coach_application(p_reseller_username text)
returns public.coach_applications
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_code text;
  v_is_coach boolean;
  v_row public.coach_applications;
begin
  if v_uid is null then
    raise exception '请先登录';
  end if;

  select is_coach into v_is_coach from public.profiles where id = v_uid;
  if not found then
    raise exception '找不到账号';
  end if;
  if v_is_coach then
    raise exception '你已经是 Journey Coach，无需再申请';
  end if;

  v_code := lower(trim(coalesce(p_reseller_username, '')));
  if v_code !~ '^[a-z0-9]{3,20}$' then
    raise exception 'Reseller Username 只能是 3-20 位英文字母或数字';
  end if;

  if exists (select 1 from public.coach_applications where applicant_id = v_uid and status = 'pending') then
    raise exception '你已有一个待审核的申请';
  end if;

  insert into public.coach_applications (applicant_id, reseller_username, status)
  values (v_uid, v_code, 'pending')
  returning * into v_row;

  return v_row;
end;
$$;

revoke execute on function public.submit_coach_application(text) from anon, public;
grant execute on function public.submit_coach_application(text) to authenticated;

-- Withdraw one's own pending application. Returns it to "Not Applied"; a new
-- application may be submitted immediately.
create or replace function public.withdraw_coach_application(p_application_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
begin
  update public.coach_applications
     set status = 'withdrawn'
   where id = p_application_id and applicant_id = v_uid and status = 'pending';
  if not found then
    raise exception '找不到可撤回的申请';
  end if;
end;
$$;

revoke execute on function public.withdraw_coach_application(uuid) from anon, public;
grant execute on function public.withdraw_coach_application(uuid) to authenticated;

-- The caller's own application history, WITHOUT internal_note (Admin-only).
create or replace function public.get_my_coach_applications()
returns table (
  id uuid,
  application_number bigint,
  reseller_username text,
  status public.coach_application_status,
  reject_reason text,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select id, application_number, reseller_username, status, reject_reason,
         submitted_at, reviewed_at, created_at
    from public.coach_applications
   where applicant_id = auth.uid()
   order by submitted_at desc;
$$;

revoke execute on function public.get_my_coach_applications() from anon, public;
grant execute on function public.get_my_coach_applications() to authenticated;

-- Mark one of the caller's own notifications as read.
create or replace function public.mark_notification_read(p_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.notifications
     set read_at = now()
   where id = p_id and user_id = auth.uid() and read_at is null;
$$;

revoke execute on function public.mark_notification_read(uuid) from anon, public;
grant execute on function public.mark_notification_read(uuid) to authenticated;

-- ============================================================
-- Admin-only RPCs
-- ============================================================

-- Approve: activate Coach capability via the FROZEN admin_set_coach_access()
-- (which enforces the immutable Reseller Username + uniqueness rules), then
-- mark the application approved and notify the applicant. If activation fails
-- (duplicate username, etc.) the whole transaction rolls back and the
-- application stays pending.
create or replace function public.approve_coach_application(p_application_id uuid, p_internal_note text default null)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_app public.coach_applications;
begin
  if public."current_role"() is distinct from 'admin'::public.user_role then
    raise exception '只有管理员可以审核申请';
  end if;

  select * into v_app from public.coach_applications where id = p_application_id;
  if not found then
    raise exception '找不到该申请';
  end if;
  if v_app.status <> 'pending' then
    raise exception '该申请已被处理';
  end if;

  perform public.admin_set_coach_access(v_app.applicant_id, true, v_app.reseller_username);

  update public.coach_applications
     set status = 'approved',
         reviewed_by = auth.uid(),
         reviewed_at = now(),
         internal_note = coalesce(p_internal_note, internal_note)
   where id = p_application_id;

  insert into public.notifications (user_id, type, title, body, action_label, action_href)
  values (
    v_app.applicant_id,
    'coach_application_approved',
    '恭喜！',
    '你的 Journey Coach 申请已通过。',
    '前往教练工作台',
    '/coach'
  );
end;
$$;

revoke execute on function public.approve_coach_application(uuid, text) from anon, public;
grant execute on function public.approve_coach_application(uuid, text) to authenticated;

-- Reject: requires a reason (shown to the applicant). Does NOT touch Coach
-- capability. Records reviewer + reason + optional internal note, and notifies.
create or replace function public.reject_coach_application(p_application_id uuid, p_reject_reason text, p_internal_note text default null)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_app public.coach_applications;
begin
  if public."current_role"() is distinct from 'admin'::public.user_role then
    raise exception '只有管理员可以审核申请';
  end if;
  if p_reject_reason is null or length(trim(p_reject_reason)) = 0 then
    raise exception '请填写拒绝原因';
  end if;

  select * into v_app from public.coach_applications where id = p_application_id;
  if not found then
    raise exception '找不到该申请';
  end if;
  if v_app.status <> 'pending' then
    raise exception '该申请已被处理';
  end if;

  update public.coach_applications
     set status = 'rejected',
         reject_reason = trim(p_reject_reason),
         reviewed_by = auth.uid(),
         reviewed_at = now(),
         internal_note = coalesce(p_internal_note, internal_note)
   where id = p_application_id;

  insert into public.notifications (user_id, type, title, body, reject_reason, action_label, action_href)
  values (
    v_app.applicant_id,
    'coach_application_rejected',
    '申请未通过',
    '你的 Journey Coach 申请未通过。',
    trim(p_reject_reason),
    '重新提交',
    '/customer/profile'
  );
end;
$$;

revoke execute on function public.reject_coach_application(uuid, text, text) from anon, public;
grant execute on function public.reject_coach_application(uuid, text, text) to authenticated;

-- Save an Admin-only internal note on a pending application during review.
create or replace function public.update_application_internal_note(p_application_id uuid, p_internal_note text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if public."current_role"() is distinct from 'admin'::public.user_role then
    raise exception '只有管理员可以编辑内部备注';
  end if;
  update public.coach_applications set internal_note = p_internal_note where id = p_application_id;
  if not found then
    raise exception '找不到该申请';
  end if;
end;
$$;

revoke execute on function public.update_application_internal_note(uuid, text) from anon, public;
grant execute on function public.update_application_internal_note(uuid, text) to authenticated;

-- Lightweight pending count for the Admin dashboard reminder. Returns 0 for
-- non-admins rather than raising (it is read on the dashboard).
create or replace function public.count_pending_coach_applications()
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when public."current_role"() = 'admin'::public.user_role
      then (select count(*)::int from public.coach_applications where status = 'pending')
    else 0
  end;
$$;

revoke execute on function public.count_pending_coach_applications() from anon, public;
grant execute on function public.count_pending_coach_applications() to authenticated;
